### ISSUE TITLE
:sparkles: Friend List Modal 기능 개선

### ISSUE THREAD

**Issue by KKWANH** [PPiing/frontend#118]
## 필요 기능
- friend 자체로 불러오는 것이 아닌 Nickname을 통해 api로 불러오도록 변형해야 함

## 연관 기능
- modal
- profile
- friend list

## [Optional] Description
- 내용을 적어주세요.

## [Optional] Whatever
- 내용을 적어주세요.

**Comment by muingY** [comment]
nav 모달을 통해 내 프로필로 이동했을 때 모달이 잘 닫히지 않고 화면을 한번 클릭해줘야 닫히는 문제가 있습니다.

**Comment by KKWANH** [comment]
> nav 모달을 통해 내 프로필로 이동했을 때 모달이 잘 닫히지 않고 화면을 한번 클릭해줘야 닫히는 문제가 있습니다.

modal을 통해 이동할 때 modal bool을 해제하는 작업을 넣도록 하겠습니다
