### ISSUE TITLE
:bug: 게임 룰 설정화면에서 건드리지 않고 바로 레디를 눌렀을 경우에 언디파인을 전송

### ISSUE THREAD

**Issue by jinbekim** [PPiing/frontend#149]
## Symptom
- 게임 레디 버튼을 누르게 되면 언디파인인 내용이 전송이 되게 됩니다.
 
<img width="219" alt="image" src="https://user-images.githubusercontent.com/59330110/179326743-e96a53b0-5886-4c86-8c5f-098f15f5573b.png">

**Comment by Hyunja27** [comment]
수정완료!
