### ISSUE TITLE
:bug: 메인 페이지 무한루프 개선 & socketManager 중복 제거

### ISSUE THREAD

**Issue by kyoshong** [PPiing/frontend#269]
## Symptom
- 로컬 메인페이지에서 간헐적으로 무한루프가 도는 현상 발생

**Comment by muingY** [comment]
혹시 무한루프가 로컬에서 도커 켜고 테스트할때 말씀하시는건가요?
맞다면 해당 현상은 페이지 위치와 관계없이 발생합니다.

지금은 도커를 내렸다가 다시 올리는 방법밖에 없는데, 혹시나 고치셨다면 원인 공유 부탁드려요!

**Comment by joohongpark** [comment]
혹시 로컬에서 아직도 발생하나요?

**Comment by muingY** [comment]
발생하면 말씀드릴게요

**Comment by muingY** [comment]
무한루프가 발생했어요..

**Comment by kyoshong** [comment]
확실한 원인인지는 모르겠지만 nginx reverse proxy에서 문제가 있는 것 같아 vite config의 세팅을 연결에 실패했을 시 직접 해당 프론트 포트에 연결되도록 강제 해줬습니다. 제 로컬에서는 도커 재실행시에도 무한루프였는데 해당 문제는 해결 되었습니다.
