### ISSUE TITLE
:bug: 빌드 에러 및 호스트 IP 이슈

### ISSUE THREAD

**Issue by joohongpark** [PPiing/frontend#3]
## Symptom
- 코드 에러로 인한 빌드 에러
- vite 상에서 preview 실행 시 포트 / 호스트 이슈

## Environment (OS / Browser)
- linux on docker

## [Optional] Screenshot
<img width="1351" alt="스크린샷 2022-04-28 오후 3 04 31" src="https://user-images.githubusercontent.com/27172454/165687492-99090eff-da60-44ad-9613-30c204877050.png">

## [Optional] Error Case
- 배포 명령어인 vite preview 실행 시 호스트 IP 제한으로 도커 네트워크 상 정상적으로 동작되지 않습니다.
  - 기본값이 127.0.0.1 (로컬호스트) 인데 이외의 IP에서 접근하면 접근이 되지 않습니다.
  - 모든 곳에서 요청을 받을 수 있는 0.0.0.0 으로 변경하여야 할 것으로 보입니다.
- vite preview 명령어를 사용해 프론트앤드 앱을 배포할 때 4173 포트를 기본적으로 사용하지만 명시할 필요가 있는 것 같습니다.

### 빌드 에러 이슈
코드 에러로 인한 빌드 에러이므로 코드를 수정해야 할 듯 합니다.
### host, port 이슈
- https://vitejs-kr.github.io/config/#server-host 가이드를 참조하여 `vite.config.js` 파일을 다음과 같이 변경할 때 정상 동작함을 확인하였습니다.
```typescript
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    host: "0.0.0.0",
    port: 4173,
  }
});

```

**Comment by HyeonsikBae** [comment]
@joohongpark @Hyunja27 @KKWANH 
해당 이슈 확인했습니다.
이에 대한 의견 드립니다.
몇 가지 문의 사항도 있어 명일 CI/CD 설정 시 해당 이슈에 대한 해결도 함께 진행되었으면 합니다.

1. 코드 에러
  - 폴더 트리 구조를 정하는데 예시로 추가한 임시 파일로 모든 소스 코드 파일들이 변경 및 제거 될 예정입니다.
     추후 CI/CD 설정 시 소스 코드가 문제가 된다면 삭제하고 진행해도 무관할 것 같습니다.

2. IP/PORT 명시
  - server.host를 "0.0.0.0"으로 명시 예정입니다.
  - server.port는 3000번을, preview.port는 4173번을 기본 포트로 사용하는 걸로 알고 있습니다.
    위에서 server.port를 4173번 포트로 명시하는 해결 방안 제시해주셔서 추가로 질문 드립니다.
      1) server.port와 preview.port 중 어떤 설정에 대한 변경이 필요한지 궁금합니다.
      2) 기존 도커 컴포즈를 통한 네트워크 구성에서 프론트엔드단은 3030번 포트를 사용하기로 했던 걸로 기억하는데 몇 번 포트를 사용하면 되는지 확인 부탁드립니다.

**Comment by joohongpark** [comment]
@HyeonsikBae
예 알겠습니다. 소스코드에 대해 CI/CD를 정상적으로 동작하게 하려면 lint와 build 명령어가 동작해야 해서 CI/CD 적용 전 해결하는 것이 좋을 것 같습니다. 일단 임시로 제거해주시는 것도 좋을 것 같습니다.

그리고 문의사항에 대한 답변 드립니다.
### 2-i
docker-compose를 구성해 보며 깨닿게 되었는데, 두 모드에 대해 포트가 다르게 서비스된다면 개발 모드와 배포 모드에 대해 Nginx 게이트웨이에서 네트워크 설정을 다르게 해야 하는 문제가 있습니다. 그래서 개발 모드 및 배포 모드 모두 동일한 포트에서 동작이 되는 것을 제안 드립니다.
### 2-ii
기존에 네트워크 구성을 공유드렸던 것은 임시로 만든 것이라 어느 포트를 사용해도 상관 없지만 혼동의 우려가 있으니 3030을 사용하는 것을 제안드립니다.

**Comment by joohongpark** [comment]
빌드 에러는 현재까지 고쳐지지 않은거 같습니다. 빌드 에러로 인해 앱 동작 및 배포가 불가능한 상황입니다. 조치 부탁드립니다!
