### ISSUE TITLE
:bug: 게임 내부에서 백엔드에서 주는 정보가 렌더링이 안됩니다.

### ISSUE THREAD

**Issue by KKWANH** [PPiing/frontend#310]
## Symptom
- 백엔드에서 공 위치는 잘 불러와지지만, 프론트 상으로는 공이 잘 움직이지 않습니다. 새로고침 무한번 하다보면 또 될 때도 있습니다.
- paddle 움직임도 backend에 정보가 가지만 frontend 상으로는 해결이 되지 않습니다.
- _이 상태에서는 search list에 검색을 해도 network 상으로는 불러와졌지만 렌더링이 되지 않습니다._
  -> 또 형유님 컴에선 잘되네
-> 낌 컴퓨터 문제일 수도 있을 것 같습니다. 쒯

**Comment by Hyunja27** [comment]
수정 완!료!
