### ISSUE TITLE
:sparkles: template 제작

### ISSUE THREAD

**Issue by HyeonsikBae** [PPiing/frontend#33]
## 필요 기능
- 재사용되는 요소들에 대한 템플릿 작성

## 연관 기능
- view, container

## [Optional] Description
- View, Container의 경우, 각 파일에 같은 소스 코드를 반복하여 사용 중입니다.
  반복되는 내용에 대한 코드를 아래 파일에 작성하여 재사용성을 높이는 것으로 결정되었습니다.
- /src/view/viewTemplate.tsx
- /src/container/containerTemplate.tsx

## [Optional] Whatever
- 내용을 적어주세요.

**Comment by KKWANH** [comment]
기본 사항은 적용됬습니다 앞으로 차차 확장하면서 쓰겠죠
