### ISSUE TITLE
:bug: server error - scroll

### ISSUE THREAD

**Issue by HyeonsikBae** [PPiing/frontend#35]
## Symptom
- server에 접속 시, 전체 화면에 대한 scroll 발생
- Mac / Chrome, Mac / FireFox 에서는 발견되지 않은 것으로 보아 여러 환경에서 추가 확인하면 좋을 것 같습니다.

## Environment (OS / Browser)
- Linux / Chrome
- Linux / FireFox
- Windows / Chrome

## [Optional] How To Solve
- 내용을 적어주세요.

**Comment by muingY** [comment]
해결!
